server:
  port: 8081
github:
  baseUrl: https://api.github.com
  user.repos.url: /users/{userName}/repos?page_size=100&type=public
  org.repos.url: /orgs/{orgName}/repos?page_size=100&type=public
  token:
  max.commits: 20
